name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # At 06:06 UTC on Monday
    - cron: "6 6 * * 1"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SING_BOX_VERSION: 1.12.8
jobs:
  v2ray-rules-dat:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install sing-box ${{ env.SING_BOX_VERSION }}
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh -s -- --version "${{ env.SING_BOX_VERSION }}"
          sing-box version

      - name: Build json rule-set
        run: |
          go run -v .

      - name: Build srs rule-set
        working-directory: rule-set
        run: |
          for i in *.json; do
            echo "[INFO] compile $i"
            sing-box rule-set compile "$i"
          done

      - name: Git push assets to "release" branch
        working-directory: rule-set
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "Update rule-set"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

  sukka-ruleset:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: merge.sh

      - name: Checkout ruleset
        uses: actions/checkout@v6
        with:
          repository: 'SukkaLab/ruleset.skk.moe'
          path: prebuild
          sparse-checkout: |
            sing-box/domainset
            sing-box/non_ip

      - name: Install sing-box ${{ env.SING_BOX_VERSION }}
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh -s -- --version "${{ env.SING_BOX_VERSION }}"
          sing-box version

      - name: Merge rule-set
        run: |
          chmod +x merge.sh
          ./merge.sh

      - name: Build srs rule-set
        working-directory: public
        run: |
          for i in *.json; do
            echo "[INFO] compile $i"
            sing-box rule-set compile "$i"
          done

      - name: Git push assets to "release2" branch
        working-directory: public
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release2
          git add .
          git commit -m "Update rule-set"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release2
